// Mock data for Paytm clone

export const currentUser = {
  id: 'user_001',
  name: 'Priya Sharma',
  mobile: '9876543210',
  email: 'priya@example.com',
  upiId: 'priya.sharma@paytm',
  balance: 45230,
  profileImage: '👤',
};

export const transactions = [
  {
    id: 'txn_001',
    type: 'sent',
    recipient: 'Rahul Kumar',
    phone: '9123456789',
    amount: 500,
    date: '2024-04-02',
    status: 'completed',
    upiRef: 'TXN123456789',
  },
  {
    id: 'txn_002',
    type: 'received',
    sender: 'Amit Singh',
    phone: '9234567890',
    amount: 1000,
    date: '2024-04-01',
    status: 'completed',
    upiRef: 'TXN123456790',
  },
  {
    id: 'txn_003',
    type: 'sent',
    recipient: 'Neha Gupta',
    phone: '9345678901',
    amount: 250,
    date: '2024-03-31',
    status: 'completed',
    upiRef: 'TXN123456791',
  },
  {
    id: 'txn_004',
    type: 'sent',
    recipient: 'Vikas Patel',
    phone: '9456789012',
    amount: 2000,
    date: '2024-03-30',
    status: 'completed',
    upiRef: 'TXN123456792',
  },
  {
    id: 'txn_005',
    type: 'received',
    sender: 'Divya Reddy',
    phone: '9567890123',
    amount: 500,
    date: '2024-03-29',
    status: 'completed',
    upiRef: 'TXN123456793',
  },
  {
    id: 'txn_006',
    type: 'sent',
    recipient: 'Rohan Desai',
    phone: '9678901234',
    amount: 150,
    date: '2024-03-28',
    status: 'completed',
    upiRef: 'TXN123456794',
  },
  {
    id: 'txn_007',
    type: 'bill_payment',
    billType: 'electricity',
    provider: 'BESCOM',
    amount: 1500,
    date: '2024-03-27',
    status: 'completed',
    upiRef: 'TXN123456795',
  },
  {
    id: 'txn_008',
    type: 'received',
    sender: 'Pooja Verma',
    phone: '9789012345',
    amount: 300,
    date: '2024-03-26',
    status: 'completed',
    upiRef: 'TXN123456796',
  },
];

export const bills = [
  {
    id: 'bill_001',
    category: 'electricity',
    name: 'Electricity Bill',
    icon: '⚡',
    providers: [
      { id: 'bescom', name: 'BESCOM', description: 'Karnataka Electricity Board' },
      { id: 'teda', name: 'TEDA', description: 'Telangana Electricity Distribution' },
      { id: 'msedcl', name: 'MSEDCL', description: 'Maharashtra State Electricity' },
    ],
  },
  {
    id: 'bill_002',
    category: 'mobile',
    name: 'Mobile Recharge',
    icon: '📱',
    providers: [
      { id: 'jio', name: 'Jio', description: 'Reliance Jio prepaid' },
      { id: 'airtel', name: 'Airtel', description: 'Airtel prepaid' },
      { id: 'vodafone', name: 'Vodafone', description: 'Vodafone prepaid' },
      { id: 'idea', name: 'Idea', description: 'Idea prepaid' },
    ],
  },
  {
    id: 'bill_003',
    category: 'water',
    name: 'Water Bill',
    icon: '💧',
    providers: [
      { id: 'bwssb', name: 'BWSSB', description: 'Bangalore Water Supply' },
      { id: 'gwssb', name: 'GWSSB', description: 'Gujarat Water Supply' },
    ],
  },
  {
    id: 'bill_004',
    category: 'fastag',
    name: 'FasTag',
    icon: '🛣️',
    description: 'Recharge your FasTag wallet',
  },
  {
    id: 'bill_005',
    category: 'internet',
    name: 'Broadband',
    icon: '🌐',
    providers: [
      { id: 'airtel', name: 'Airtel Broadband', description: 'High-speed internet' },
      { id: 'jio', name: 'Jio Fiber', description: 'Fiber broadband' },
    ],
  },
];

export const flights = [
  {
    id: 'flight_001',
    from: 'BLR',
    to: 'DEL',
    date: '2024-04-15',
    departure: '06:00',
    arrival: '09:30',
    duration: '3h 30m',
    airline: 'IndiGo',
    flightNumber: '6E1234',
    price: 3500,
    seats: 45,
    image: '✈️',
  },
  {
    id: 'flight_002',
    from: 'BLR',
    to: 'DEL',
    date: '2024-04-15',
    departure: '09:00',
    arrival: '12:30',
    duration: '3h 30m',
    airline: 'SpiceJet',
    flightNumber: 'SG2456',
    price: 2999,
    seats: 23,
    image: '✈️',
  },
  {
    id: 'flight_003',
    from: 'BLR',
    to: 'DEL',
    date: '2024-04-15',
    departure: '14:30',
    arrival: '18:00',
    duration: '3h 30m',
    airline: 'Air India',
    flightNumber: 'AI345',
    price: 4200,
    seats: 67,
    image: '✈️',
  },
  {
    id: 'flight_004',
    from: 'BLR',
    to: 'DEL',
    date: '2024-04-15',
    departure: '18:00',
    arrival: '21:30',
    duration: '3h 30m',
    airline: 'Vistara',
    flightNumber: 'UK789',
    price: 4800,
    seats: 34,
    image: '✈️',
  },
  {
    id: 'flight_005',
    from: 'BLR',
    to: 'DEL',
    date: '2024-04-15',
    departure: '20:00',
    arrival: '23:30',
    duration: '3h 30m',
    airline: 'Go Air',
    flightNumber: 'G8567',
    price: 3200,
    seats: 12,
    image: '✈️',
  },
];

export const financialServices = [
  {
    id: 'service_001',
    name: 'Credit Card',
    icon: '💳',
    description: 'Get a credit card with rewards and cashback',
    color: 'bg-blue-100',
  },
  {
    id: 'service_002',
    name: 'Insurance',
    icon: '🛡️',
    description: 'Health, travel, and life insurance plans',
    color: 'bg-green-100',
  },
  {
    id: 'service_003',
    name: 'Investments',
    icon: '📈',
    description: 'Mutual funds and investment portfolios',
    color: 'bg-purple-100',
  },
  {
    id: 'service_004',
    name: 'Loans',
    icon: '🏦',
    description: 'Personal loans at competitive interest rates',
    color: 'bg-orange-100',
  },
  {
    id: 'service_005',
    name: 'Savings Account',
    icon: '💰',
    description: 'Digital savings account with high interest',
    color: 'bg-indigo-100',
  },
];

export const merchantData = {
  userId: 'merchant_001',
  name: 'TechHub Store',
  email: 'contact@techhub.com',
  phone: '9876543210',
  upiId: 'techhub@paytm',
  totalRevenue: 156750,
  todayRevenue: 12450,
  todayTransactions: 34,
  monthlyTransactions: 892,
  stats: {
    monthlyRevenue: 156750,
    weeklyRevenue: 38420,
    todayRevenue: 12450,
    totalTransactions: 892,
  },
};

export const merchantTransactions = [
  {
    id: 'merch_001',
    customerName: 'John Doe',
    amount: 450,
    date: '2024-04-02 14:30',
    status: 'completed',
    method: 'UPI',
    orderId: 'ORD123456',
  },
  {
    id: 'merch_002',
    customerName: 'Sarah Johnson',
    amount: 1200,
    date: '2024-04-02 13:15',
    status: 'completed',
    method: 'UPI',
    orderId: 'ORD123457',
  },
  {
    id: 'merch_003',
    customerName: 'Mike Chen',
    amount: 750,
    date: '2024-04-02 12:00',
    status: 'completed',
    method: 'QR Code',
    orderId: 'ORD123458',
  },
  {
    id: 'merch_004',
    customerName: 'Emma Wilson',
    amount: 320,
    date: '2024-04-02 10:45',
    status: 'completed',
    method: 'UPI',
    orderId: 'ORD123459',
  },
  {
    id: 'merch_005',
    customerName: 'David Brown',
    amount: 890,
    date: '2024-04-02 09:20',
    status: 'completed',
    method: 'QR Code',
    orderId: 'ORD123460',
  },
];
